"""Convert tshark's CSV file to CSV and JSON adapted.
This script reads a CSV file generated by tshark, modifies specific fields,
adds new columns, and writes the modified data to a new CSV file and a JSON file.

It processes fields such as IP headers, TCP/UDP/ICMP information, and payload data,
converting them to appropriate formats and adding relevant metadata.

The payload data is extracted and stored in hex format, using only one one payload
field per packet.
"""
import argparse
import csv
import lzma
import os
import sys
import logging
import gzip
import json


# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(levelname)s - %(message)s"
)

# Fields must be aligned with 01_pcap_to_csvtshark.py
TSHARK_FIELDS = [
    'timestamp',
    'ip_version', 'ip_ihl', 'ip_orig_tos', 'ip_tos',
    'ip_dscp',
    'ip_enc', 'ip_len', 'ip_id', 'ip_orig_flags', 'ip_flag_MF', 'ip_flag_DF',
    'ip_flag_Error', 'ip_frag', 'ip_ttl', 'ip_proto', 'ip_chksum', 'ip_src',
    'ip_dst',
    'icmp_type', 'icmp_code', 'icmp_id', 'icmp_seq', 'icmp_chksum',
    'udp_sport', 'udp_dport', 'udp_len', 'udp_chksum', 'tcp_sport',
    'tcp_dport', 'tcp_seq', 'tcp_ack', 'tcp_orig_flags', 'tcp_CWR',
    'tcp_ACK_flag', 'tcp_PSH', 'tcp_RST', 'tcp_SYN', 'tcp_URG', 'tcp_FIN',
    'tcp_ECE', 'tcp_other_flags', 'tcp_window',
    'tcp_chksum', 'tcp_urgptr',
    'tcp_options', 'udp_payload', 'tcp_payload', 'icmp_payload', 'ip_payload']

# These fields must be aligned with 05_ip_reassembly/coldefinitions.py
MODIFIED_FIELDS = [
    'timestamp',
    'ip_version', 'ip_ihl', 'ip_orig_tos', 'ip_tos',
    'ip_prec',
    'ip_dscp',
    'ip_enc', 'ip_len', 'ip_id', 'ip_orig_flags', 'ip_flag_MF', 'ip_flag_DF',
    'ip_flag_Error', 'ip_frag', 'ip_ttl', 'ip_proto', 'ip_chksum', 'ip_src',
    'ip_dst',
    'ip_options',
    'icmp_type', 'icmp_code', 'icmp_id', 'icmp_seq', 'icmp_chksum',
    'udp_sport', 'udp_dport', 'udp_len', 'udp_chksum',
    'tcp_sport', 'tcp_dport', 'tcp_seq', 'tcp_ack',
    'tcp_dataofs', 'tcp_reserved', 'tcp_orig_flags', 'tcp_CWR',
    'tcp_ACK_flag', 'tcp_PSH', 'tcp_RST', 'tcp_SYN', 'tcp_URG', 'tcp_FIN',
    'tcp_ECE', 'tcp_NS', 'tcp_other_flags', 'tcp_window',
    'tcp_chksum', 'tcp_urgptr', 'tcp_options', 'payload_hex',
    'key', 'IBR_info']


def add_primary_fields(row, json_data, csv_data):
    """
    Add the primary fields to the JSON data.
    """
    # if "timestamp" in row:
    json_data["timestamp"] = row["timestamp"]  #[:-3]  # Remove milliseconds
    row['ip_id'] = int(row["ip_id"], 16)  # Convert from hex to decimal
    json_data["ip_id"] = row['ip_id']

    return json_data, csv_data

def add_ihl_info(row, json_data, csv_data):
    if row["ip_ihl"].isdigit():
        ip_ihl_int = str(int(row["ip_ihl"]) // 4)
        ip_ihl_dec = str(int(row["ip_ihl"]) / 4)
        if float(ip_ihl_int) == float(ip_ihl_dec):
            json_data["ip_ihl"] = ip_ihl_int
            json_data["ip_ihl_ok"] = True
            csv_data["ip_ihl_ok"] = True
        else:
            json_data["ip_ihl_int"] = ip_ihl_int
            json_data["ip_ihl_dec"] = ip_ihl_dec
            json_data["ip_ihl_ok"] = False
            csv_data["ip_ihl_int"] = ip_ihl_int
            csv_data["ip_ihl_dec"] = ip_ihl_dec
            csv_data["ip_ihl_ok"] = False

    else:
        json_data["ip_ihl_raw"] = row["ip_ihl"]
        json_data["ip_ihl_ok"] = False
        csv_data["ip_ihl_ok"] = False

    return json_data, csv_data


def add_ip_info(row, json_data, csv_data):
    """
    Add the IP fields to the JSON data.
    """
    # JSON
    json_data["ip_version"] = int(row["ip_version"])
    json_data["ip_orig_tos"] = row["ip_orig_tos"]
    json_data["ip_tos"] = row["ip_tos"]
    json_data["ip_dscp"] = row["ip_dscp"]
    json_data["ip_enc"] = row["ip_enc"]
    json_data["ip_len"] = int(row["ip_len"])
    json_data["ip_frag"] = row["ip_frag"]
    json_data["ip_ttl"] = row["ip_ttl"]
    json_data["ip_proto"] = int(row["ip_proto"])
    json_data["ip_src"] = row["ip_src"]
    json_data["ip_dst"] = row["ip_dst"]

    # CSV - Convert to int
    row["ip_version"] = int(row["ip_version"])
    row["ip_len"] = int(row["ip_len"])
    row["ip_proto"] = int(row["ip_proto"])

    return json_data, csv_data


def add_tcp_info(row, json_data, csv_data):
    """

    Add the TCP fields to the JSON data.

    Args:
        row (dict): The row data.
        json_data (dict): The JSON data.

    Returns:
        dict: The updated JSON data.
    """
    if len(row["tcp_sport"]) > 0:
        row["tcp_sport"] = int(row["tcp_sport"])
        json_data["tcp_sport"] = row["tcp_sport"]
    if len(row["tcp_dport"]) > 0:
        row["tcp_dport"] = int(row["tcp_dport"])
        json_data["tcp_dport"] = row["tcp_dport"]
    if len(row["tcp_seq"]) > 0:
        row["tcp_seq"] = int(row["tcp_seq"])
        json_data["tcp_seq"] = row["tcp_seq"]
    if len(row["tcp_ack"]) > 0:
        row["tcp_ack"] = int(row["tcp_ack"])
        json_data["tcp_ack"] = row["tcp_ack"]
    if len(row["tcp_window"]) > 0:
        row["tcp_window"] = int(row["tcp_window"])
        json_data["tcp_window"] = row["tcp_window"]
    if len(row["tcp_urgptr"]) > 0:
        row["tcp_urgptr"] = int(row["tcp_urgptr"])
        json_data["tcp_urgptr"] = row["tcp_urgptr"]
    if len(row["tcp_options"]) > 0:
        json_data["tcp_options"] = row["tcp_options"]

    return json_data, csv_data


def add_tcp_flags_info(row, json_data, csv_data):
    """
    Add the TCP fields to the JSON data.

    Args:
        row (dict): The row data.
        json_data (dict): The JSON data.

    Returns:
        dict: The updated JSON data.
    """
    if json_data['ip_proto'] != 6:
        return json_data, csv_data

    """
    # Debugging prints
    print(f"{row['tcp_orig_flags']} ACK:{row['tcp_ACK_flag']} "
          f"PSH:{row['tcp_PSH']} RST:{row['tcp_RST']} SYN:{row['tcp_SYN']} "
          f"URG:{row['tcp_URG']} FIN:{row['tcp_FIN']} ECE:{row['tcp_ECE']} "
          f"CWR:{row['tcp_CWR']} NS in:{row['tcp_other_flags']}")
    print(f"Types: {type(row['tcp_orig_flags'])} {type(row['tcp_ACK_flag'])} "
          f"{type(row['tcp_PSH'])} {type(row['tcp_RST'])} {type(row['tcp_SYN'])} "
          f"{type(row['tcp_URG'])} {type(row['tcp_FIN'])} {type(row['tcp_ECE'])} "
          f"{type(row['tcp_CWR'])} {type(row['tcp_other_flags'])}")
    """

    if row['tcp_ACK_flag'] == 'True':
        row['tcp_ACK_flag'] = True
        json_data['tcp_ACK_flag'] = True
    else:
        row['tcp_ACK_flag'] = False
        json_data['tcp_ACK_flag'] = False

    if row['tcp_PSH'] == 'True':
        row['tcp_PSH'] = True
        json_data['tcp_PSH'] = True
    else:
        row['tcp_PSH'] = False
        json_data['tcp_PSH'] = False

    if row['tcp_RST'] == 'True':
        row['tcp_RST'] = True
        json_data['tcp_RST'] = True
    else:
        row['tcp_RST'] = False
        json_data['tcp_RST'] = False

    if row['tcp_SYN'] == 'True':
        row['tcp_SYN'] = True
        json_data['tcp_SYN'] = True
    else:
        row['tcp_SYN'] = False
        json_data['tcp_SYN'] = False

    if row['tcp_URG'] == 'True':
        row['tcp_URG'] = True
        json_data['tcp_URG'] = True
    else:
        row['tcp_URG'] = False
        json_data['tcp_URG'] = False

    if row['tcp_FIN'] == 'True':
        row['tcp_FIN'] = True
        json_data['tcp_FIN'] = True
    else:
        row['tcp_FIN'] = False
        json_data['tcp_FIN'] = False

    if row['tcp_ECE'] == 'True':
        row['tcp_ECE'] = True
        json_data['tcp_ECE'] = True
    else:
        row['tcp_ECE'] = False
        json_data['tcp_ECE'] = False

    if row['tcp_CWR'] == 'True':
        row['tcp_CWR'] = True
        json_data['tcp_CWR'] = True
    else:
        row['tcp_CWR'] = False
        json_data['tcp_CWR'] = False

    if "tcp_other_flags" in row and "N" in row["tcp_other_flags"]:
        row['tcp_NS'] = True
        json_data["tcp_NS"] = True
    else:
        row['tcp_NS'] = False
        json_data["tcp_NS"] = False

    # Include the original flags
    json_data["tcp_orig_flags"] = row["tcp_orig_flags"]

    # TCP flags -> Convert to string from tcp_other_flags
    # Remove all flags found in the string
    row["tcp_other_flags"] = row["tcp_other_flags"].replace("Â·", "")
    row["tcp_other_flags"] = row["tcp_other_flags"].replace("·", "")
    row["tcp_other_flags"] = row["tcp_other_flags"].replace("E", "")
    row["tcp_other_flags"] = row["tcp_other_flags"].replace("S", "")
    row["tcp_other_flags"] = row["tcp_other_flags"].replace("A", "")
    row["tcp_other_flags"] = row["tcp_other_flags"].replace("P", "")
    row["tcp_other_flags"] = row["tcp_other_flags"].replace("R", "")
    row["tcp_other_flags"] = row["tcp_other_flags"].replace("U", "")
    row["tcp_other_flags"] = row["tcp_other_flags"].replace("F", "")
    row["tcp_other_flags"] = row["tcp_other_flags"].replace("C", "")
    row["tcp_other_flags"] = row["tcp_other_flags"].replace("N", "")

    if len(row["tcp_other_flags"]) > 0:
        json_data["tcp_other_flags"] = row["tcp_other_flags"]

    return json_data, csv_data


def add_udp_info(row, json_data, csv_data):
    """
    Add the UDP fields to the JSON data.
    """
    if len(row["udp_sport"]) > 0:
        row["udp_sport"] = int(row["udp_sport"])
        json_data["udp_sport"] = row["udp_sport"]
    if len(row["udp_dport"]) > 0:
        row["udp_dport"] = int(row["udp_dport"])
        json_data["udp_dport"] = row["udp_dport"]
    if len(row["udp_len"]) > 0:
        row["udp_len"] = int(row["udp_len"])
        json_data["udp_len"] = row["udp_len"]

    return json_data, csv_data


def add_icmp_info(row, json_data, csv_data):
    """
    Add the ICMP fields to the JSON data.
    """
    if len(row["icmp_type"]) > 0:
        row["icmp_type"] = int(row["icmp_type"])
        json_data["icmp_type"] = row["icmp_type"]
    if len(row["icmp_code"]) > 0:
        row["icmp_code"] = int(row["icmp_code"])
        json_data["icmp_code"] = row["icmp_code"]
    if len(row["icmp_id"]) > 0:
        row["icmp_id"] = int(row["icmp_id"])
        json_data["icmp_id"] = row["icmp_id"]
    if len(row["icmp_seq"]) > 0:
        row["icmp_seq"] = int(row["icmp_seq"])
        json_data["icmp_seq"] = row["icmp_seq"]

    return json_data, csv_data


def add_ip_flags_info(row, json_data, csv_data):

    if row["ip_flag_MF"] == "True":
        row["ip_flag_MF"] = True
        json_data["ip_flag_MF"] = True
    else:
        row["ip_flag_MF"] = False
        json_data["ip_flag_MF"] = False

    if row["ip_flag_DF"] == "True":
        row["ip_flag_DF"] = True
        json_data["ip_flag_DF"] = True
    else:
        row["ip_flag_DF"] = False
        json_data["ip_flag_DF"] = False

    if row["ip_orig_flags"] != "0x00" and \
        row["ip_orig_flags"] != "0x01" and \
        row["ip_orig_flags"] != "0x02" and \
        row["ip_orig_flags"] != "0x03":
        json_data["ip_orig_flags"] = row["ip_orig_flags"]
        json_data["ip_orig_flags_ok"] = False
        csv_data["ip_orig_flags_ok"] = False
    else:
        json_data["ip_orig_flags"] = row["ip_orig_flags"]
        json_data["ip_orig_flags_ok"] = True
        csv_data["ip_orig_flags_ok"] = True

    return json_data, csv_data


def convert_checksums_to_int(row, json_data, csv_data):
    # Convert from hex to decimal
    if len(row["ip_chksum"]) > 0:
        row["ip_chksum"] = str(int(row["ip_chksum"], 16))
        json_data["ip_chksum"] = row["ip_chksum"]
    if len(row["tcp_chksum"]) > 0:
        row["tcp_chksum"] = str(int(row["tcp_chksum"], 16))
        json_data["tcp_chksum"] = row["tcp_chksum"]
    if len(row["udp_chksum"]) > 0:
        row["udp_chksum"] = str(int(row["udp_chksum"], 16))
        json_data["udp_chksum"] = row["udp_chksum"]
    if len(row["icmp_chksum"]) > 0:
        row["icmp_chksum"] = str(int(row["icmp_chksum"], 16))
        json_data["icmp_chksum"] = row["icmp_chksum"]

    return json_data, csv_data


def add_payload_info(row, json_data, csv_data):
    """
    This function read the different payloads and add them to the json_data
    in the row, in hex format and in bytes format.
    """
    if len(row["icmp_payload"]) > 0:
        payload_hex = row["icmp_payload"]
        payload_type = "icmp"  # or fragmented packet
    elif len(row["udp_payload"]) > 0:
        payload_hex = row["udp_payload"]
        payload_type = "udp"
    elif len(row["tcp_payload"]) > 0:
        payload_hex = row["tcp_payload"]
        payload_type = "tcp"
    elif len(row["ip_payload"]) > 0:
        payload_hex = row["ip_payload"]
        payload_type = "ip"
    else:
        payload_hex = ""
        payload_type = ""

    # Remove the payload fields from the row
    del row["icmp_payload"]
    del row["udp_payload"]
    del row["tcp_payload"]
    del row["ip_payload"]

    json_data["payload_hex"] = payload_hex
    json_data["payload_type"] = payload_type
    row["payload_hex"] = payload_hex
    csv_data["payload_type"] = payload_type

    return json_data, csv_data


def add_key(row, index, filename=None):
    """
    This function adds the key to the entry
    """
    # Add a key column by concatenating timestamp and the dataframe key
    if filename is None:
        key = row['timestamp'] + '_' + str(index)
    else:
        key = filename + '_' + row['timestamp'] + '_' + str(index)

    return key


def process_csv(input_file, output_file_json, output_file_csv, no_gzip=False, json_output=False, long_key=False):
    """
    Process a CSV file, modify specific fields, add new columns, and write to a new file."
    :param input_file: Input CSV file (.csv, .csv.gz)
    :param output_file_json: Output JSON file (.json, .json.gz)
    :param output_file_csv: Output CSV file (.csv, .csv.gz)
    :param no_gzip: If True, do not compress output chunks
    :param long_key: If True, include the filename in the key
    """
    logging.info(f"Processing file: {input_file}")

    # If input file is compressed, open accordingly
    if input_file.endswith(".gz"):
        logging.info(f"Opening gz compressed {input_file}...")
        f_in = gzip.open(input_file, "rt", newline='', encoding="utf-8")
    elif input_file.endswith(".xz"):
        logging.info(f"Opening xz compressed {input_file}...")
        f_in = lzma.open(input_file, "rt", newline='', encoding="utf-8")
    else:
        logging.info(f"Opening uncompressed {input_file}...")
        f_in = open(input_file, "r", newline='', encoding="utf-8")

    # Output files
    if no_gzip:
        # Open uncompressed files
        f_out_csv = open(output_file_csv, "w", newline='', encoding="utf-8")
        if json_output:
            f_out_json = open(output_file_json, "w", newline='', encoding="utf-8")
        else:
            f_out_json = None
    else:
        # Open compressed files
        f_out_csv = gzip.open(output_file_csv, "wt", newline='', encoding="utf-8")
        if json_output:
            f_out_json = gzip.open(output_file_json, "wt", newline='', encoding="utf-8")
        else:
            f_out_json = None

    with f_in:
        reader = csv.DictReader(f_in, fieldnames=TSHARK_FIELDS, delimiter=";")
        writer = csv.DictWriter(f_out_csv, fieldnames=MODIFIED_FIELDS, delimiter=";")
        index = 0

        for row in reader:
            # Create the JSON info
            json_data = {}
            csv_data = {}

            # Add info
            json_data, csv_data = add_primary_fields(row, json_data, csv_data)
            json_data, csv_data = add_ihl_info(row, json_data, csv_data)
            json_data, csv_data = add_ip_info(row, json_data, csv_data)
            json_data, csv_data = add_ip_flags_info(row, json_data, csv_data)
            json_data, csv_data = add_tcp_info(row, json_data, csv_data)
            json_data, csv_data = add_tcp_flags_info(row, json_data, csv_data)
            json_data, csv_data = add_udp_info(row, json_data, csv_data)
            json_data, csv_data = add_icmp_info(row, json_data, csv_data)
            json_data, csv_data = convert_checksums_to_int(row, json_data, csv_data)
            json_data, csv_data = add_payload_info(row, json_data, csv_data)

            # Add the key, long keys include the filename
            if long_key:
                keyname = input_file.replace('pcap.gz', '').replace('pcap.xz', '').replace('pcap', '')
                key = add_key(row, index, keyname)
            else:
                key = add_key(row, index)

            # Add the key to the CSV data
            row['key'] = key

            # Convert to JSON string
            json_str_csv = json.dumps(csv_data)

            # Add the JSON string to the row
            row['IBR_info'] = json_str_csv

            # Write JSON as one line in the output file
            if f_out_json is not None:
                f_out_json.write(json.dumps(json_data) + "\n")

            writer.writerow(row)
            index += 1

    # Close output files
    f_out_csv.close()
    if f_out_json is not None:
        f_out_json.close()
        print("Processing complete, saved files", output_file_csv, output_file_json)
    else:
        print("Processing complete, saved file", output_file_csv)


def convert_csv_to_modified_csv_gz(input_folder, output_folder, no_gzip=False, json_output=False, long_key=False):
    """
    Convert CSV files to modified CSV and JSON files.
    :param input_pattern: Input CSV file pattern (.csv, .csv.gz)
    :param output_folder: Destination folder for CSV files adapted.
    :param no_gzip: If True, do not compress output chunks
    """
    if os.path.isdir(input_folder):
        print("Processing all CSV files in folder:", input_folder)
        csv_files = [os.path.join(input_folder, f) for f in os.listdir(input_folder)
                      if f.endswith('.csv') or f.endswith('.csv.gz') or f.endswith('.csv.xz')]
        print(f"Found {len(csv_files)} files to process.")
        for csv in csv_files:
            base_name = os.path.basename(csv)
            if no_gzip:
                base_name = base_name.replace(".csv", ".csv")
                base_name = base_name.replace(".csv.gz", ".csv")
                base_name = base_name.replace(".csv.xz", ".csv")
                output_file_csv = os.path.join(output_folder, base_name.replace(".csv", "_mod.csv"))
                output_file_json = os.path.join(output_folder, base_name.replace(".csv", "_mod.json"))
            else:
                base_name = base_name.replace(".csv", ".csv.gz")
                base_name = base_name.replace(".csv.gz", ".csv.gz")
                base_name = base_name.replace(".csv.xz", ".csv.gz")
                output_file_csv = os.path.join(output_folder, base_name.replace(".csv.gz", "_mod.csv.gz"))
                output_file_json = os.path.join(output_folder, base_name.replace(".csv.gz", "_mod.json.gz"))

            process_csv(csv, output_file_json, output_file_csv, no_gzip, json_output, long_key)
    else:
        print("Processing single CSV file:", input_folder)
        base_name = os.path.basename(input_folder)
        if no_gzip:
            output_file_csv = os.path.join(output_folder, base_name.replace(".csv", "_mod.csv"))
            output_file_json = os.path.join(output_folder, base_name.replace(".csv", "_mod.json"))
        else:
            output_file_csv = os.path.join(output_folder, base_name.replace(".csv.gz", "_mod.csv.gz"))
            output_file_json = os.path.join(output_folder, base_name.replace(".csv.gz", "_mod.json.gz"))

        process_csv(input_folder, output_file_json, output_file_csv, no_gzip, json_output, long_key)



if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Convert tshark's CSV file to CSV adapted.")
    parser.add_argument("-g", "--no-gzip", action="store_true", help="Do not compress output chunks (default: compress)")
    parser.add_argument("-j", "--json-output", action="store_true", help="Generate JSON output file alongside CSV (default: no generate)")
    parser.add_argument("-l", "--long-key", action="store_true", help="Create a long key using the filename")
    parser.add_argument("input_folder", help="Folder or CSV file (.csv, .csv.gz)")
    parser.add_argument("output_folder", help="Destination folder for CSV files adapted.")
    args = parser.parse_args()

    if not os.path.exists(args.output_folder):
        os.makedirs(args.output_folder)
    else:
        print(f"ERROR: Output folder {args.output_folder} already exists. Please specify a non-existing folder.")
        sys.exit(1)

    convert_csv_to_modified_csv_gz(args.input_folder, args.output_folder, args.no_gzip, args.json_output, args.long_key)
